// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpFlowTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUp1() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(807, 454));
    driver.findElement(By.id("signin2")).click();
    driver.findElement(By.id("sign-username")).click();
    driver.findElement(By.id("sign-username")).sendKeys("Hi4321");
    driver.findElement(By.id("sign-password")).click();
    driver.findElement(By.id("sign-password")).sendKeys("Hi4321");
    driver.findElement(By.cssSelector("#signInModal .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Sign up successful."));
  }
  @Test
  public void signUp2() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(808, 456));
    driver.findElement(By.id("signin2")).click();
    driver.findElement(By.id("sign-username")).click();
    driver.findElement(By.id("sign-username")).sendKeys("Ligma1234");
    driver.findElement(By.id("sign-password")).click();
    driver.findElement(By.id("sign-password")).sendKeys("Ligma1234");
    driver.findElement(By.cssSelector("#signInModal .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Sign up successful."));
  }
  @Test
  public void signUp3() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(807, 454));
    driver.findElement(By.id("signin2")).click();
    driver.findElement(By.id("sign-username")).click();
    driver.findElement(By.id("sign-username")).sendKeys("Bottle1234");
    driver.findElement(By.id("sign-password")).click();
    driver.findElement(By.id("sign-password")).sendKeys("Bottle1234");
    driver.findElement(By.cssSelector("#signInModal .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Sign up successful."));
  }
}
